name: downloader
on: 
  schedule:
    - cron: '0 5 * * *'
jobs:
  day:
    runs-on: ubuntu-latest
    steps:
      - name: scrape 
        env:
          EMAIL: ${{ secrets.EMAIL }}
          USERNAME: ${{ secrets.USERNAME }}
          PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PUSH_TOKEN }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
        run: |
        pip install requests
        python scripts/scrape.py
        git config --global user.name "$USERNAME"
        git config user.email "$EMAIL"
        git commit -am "Updated Nexar"
        git push
      